- name: Ensure .ssh directory exists
  file:
    path: /home/ubuntu/.ssh
    state: directory
    mode: 0700
    owner: ubuntu
    group: ubuntu

- name: Add Jenkins master public key to authorized_keys
  copy:
    content: "{{ hostvars['master'].jenkins_public_key }}"
    dest: /home/ubuntu/.ssh/authorized_keys
    owner: ubuntu
    group: ubuntu
    mode: 0600
