- name: Add Jenkins GPG key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Enable and start Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Create .ssh folder for jenkins
  file:
    path: /var/lib/jenkins/.ssh
    state: directory
    mode: 0700
    owner: jenkins
    group: jenkins

- name: Generate SSH keypair for Jenkins
  command: ssh-keygen -t rsa -b 4096 -f /var/lib/jenkins/.ssh/id_rsa -N ""
  args:
    creates: /var/lib/jenkins/.ssh/id_rsa

- name: Ensure ownership for jenkins .ssh
  file:
    path: /var/lib/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes


- name: Read Jenkins public key
  slurp:
    src: /var/lib/jenkins/.ssh/id_rsa.pub
  register: jenkins_pubkey

- name: Set fact to share with agent
  set_fact:
    jenkins_public_key: "{{ jenkins_pubkey.content | b64decode }}"
